# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "almalinux" do |vm|
    vm.vm.box = "almalinux/9"
    vm.vm.hostname = "almalinux"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "kalilinux" do |vm|
    vm.vm.box = "kalilinux/rolling"
    vm.vm.hostname = "kalilinux"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
